---
- name: install pgdg-centos10-10-2 PostgreSQL repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-6-x86_64/pgdg-centos10-10-2.noarch.rpm
    
    state: present
  become: yes
  when: not centos_7_installed

- name: install pgdg-centos10-10-2 PostgreSQL repository
  yum:
    name: https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    state: present
  become: yes
  when: centos_7_installed

- import_role: 
    name: geerlingguy.postgresql
  vars:
    postgresql_enablerepo: pgdg10
    postgresql_version: 10
    postgresql_data_dir: /var/lib/pgsql/10/data
    postgresql_bin_path: /usr/pgsql-10/bin
    postgresql_config_path: /var/lib/pgsql/10/data
    postgresql_daemon: postgresql-10
    postgresql_packages:
    - postgresql10
    - postgresql10-server
    - postgresql10-libs
    - postgresql10-contrib
    - postgresql10-devel

