---
- include_role: 
    name: geerlingguy.apache
  vars:
    apache_allow_override: "All"
    apache_document_root: "/var/www/html"
    apache_mods_enabled:
      - rewrite.load
    apache_listen_port: 80
    apache_vhosts:
      - servername: "localhost"
        documentroot: '{{ apache_document_root }}'
        extra_parameters: |
                  Redirect permanent / https://{{apache_host_fqdn}}:{{apache_host_ssl_port}}/
    apache_listen_port_ssl: 443
    apache_vhosts_filename: "ssl.conf"
    apache_global_vhost_settings: | 
      LoadModule ssl_module modules/mod_ssl.so 
      Listen 443 
      SSLPassPhraseDialog builtin 
      SSLSessionCache shmcb:/var/cache/mod_ssl/scache(512000) 
      SSLSessionCacheTimeout 300 
      SSLMutex default 
      SSLRandomSeed startup file:/dev/urandom 256 
      SSLRandomSeed connect builtin 
      SSLCryptoDevice builtin
      SSLProxyEngine on
    apache_vhosts_ssl: "{{ lookup('vars','apache_vhosts_ssl_with_chain_apache22') if (apache_ssl_use_chain) else lookup('vars','apache_vhosts_ssl_without_chain_apache22')}}"
