---
- import_role: 
    name: geerlingguy.apache
  vars:
    apache_vhosts_ssl:
      - servername: "{{host_fqdn}}"
        documentroot: '{{ apache_document_root }}'
        certificate_file: "{{ ssl_crt }}"
        certificate_key_file: "{{ ssl_key }}"
        extra_parameters: |
                  <IfModule mod_headers.c>
                    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
                  </IfModule>
                  ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/html"
