---
- hosts: vagrant
  user: vagrant
  become: yes
  roles:
    - role: postgresql
      tags: postgresql
    - role: apache
      tags: apache
    - role: php
      tags: php
    - role: prometheus
      tags: prometheus
    - role: redis
      tags: redis
    - role: nextcloud
      tags: nextcloud

- hosts: remotes
  become: yes
  roles:
    - role: postgresql
      tags: postgresql
    - role: apache
      tags: apache
    - role: php
      tags: php
    - role: prometheus
      tags: prometheus
    - role: redis
      tags: redis
    - role: nextcloud
      tags: nextcloud
