---
- hosts: vagrant
  user: vagrant
  become: yes
  vars:
    server_env: vagrant
  roles:
    - role: postgresql
      tags: pg
    - role: apache
      tags: apache
    - role: php
      tags: php
    - role: geerlingguy.redis
    - role: nextcloud

- hosts: remotes
  become: yes
  roles:
    - role: postgresql
      tags: pg
    - role: apache
      tags: apache
    - role: php
      tags: php
    - role: geerlingguy.redis
    - role: nextcloud
