---
# Ansible Galaxy roles.
- src: geerlingguy.postgresql
  version: 1.4.5
- src: geerlingguy.apache
  version: 3.0.3
- src: geerlingguy.apache-php-fpm
  version: 1.1.0
- src: geerlingguy.php
  version: 3.7.0
- src: geerlingguy.php-versions
  version: 3.0.0
- src: geerlingguy.redis
  version: 1.6.0
- src: geerlingguy.repo-epel
  version: 1.2.3
- src: geerlingguy.repo-remi
  version: 1.2.0
- src: https://github.com/jaredboone/ansible-role-prometheus
  name: jaredboone.prometheus