---
# Ansible Galaxy roles.
- src: geerlingguy.postgresql
  version: 1.4.5
- src: geerlingguy.apache
  version: 3.0.3
- src: geerlingguy.apache-php-fpm
  version: 1.1.0
- src: geerlingguy.php
  version: 3.7.0
- src: geerlingguy.php-versions
  version: 3.0.0
- src: geerlingguy.redis
  version: 1.6.0
- src: geerlingguy.repo-epel
  version: 1.2.3
- src: geerlingguy.repo-remi
  version: 1.2.0
- src: https://github.com/jaredboone/ansible-role-prometheus
  name: jaredboone.prometheus
- src: https://github.com/jaredboone/ansible-role-nextcloud
  name: jaredboone.nextcloud
- src: https://github.com/jaredboone/ansible-role-nextcloud-upgrade
  name: jaredboone.nextcloud-upgrade
- src: https://github.com/jaredboone/ansible-role-nextcloud-backup
  name: jaredboone.nextcloud-backup
- src: https://github.com/jaredboone/ansible-role-postgresql-pgdg95
  name: jaredboone.postgresql-pgdg95
- src: https://github.com/jaredboone/ansible-role-postgresql-pgdg10
  name: jaredboone.postgresql-pgdg10
- src: https://github.com/jaredboone/ansible-role-apache-2.2
  name: jaredboone.apache-2.2
- src: https://github.com/jaredboone/ansible-role-apache-2.4
  name: jaredboone.apache-2.4
- src: https://github.com/jaredboone/ansible-role-php-fpm-remi
  name: jaredboone.php-fpm-remi