---
# install.yml

- name: install - ensure nextcloud is unarchived in {{ nextcloud_web_root }}
  unarchive:
    src: '{{ nextcloud_repo_url  }}/{{ nextcloud_version }}.tar.bz2'
    extra_opts:
      - '--strip-components=1'
      - '--show-stored-names'
    remote_src: true
    dest: '{{ nextcloud_web_root }}'

- import_tasks: 'permissions.yml'
  tags: nextcloud

- name: install - ensure nextcloud install is finished
  command: 'php {{ nextcloud_web_root }}/occ maintenance:install --database "pgsql" --database-name "{{ nextcloud_postgres_db }}"  --database-user "{{ nextcloud_postgres_user }}" --database-pass "{{ nextcloud_postgres_pw }}" --admin-user "{{ nextcloud_admin_user }}" --admin-pass "{{ nextcloud_admin_pw }}" --data-dir "{{ nextcloud_data_root }}"'
  become: true
  become_user: apache

