---
# upgrade
- name: ensure nextcloud is in maintenance mode
  command: 'php {{ nextcloud_install_dir }}/occ maintenance:mode --on'
  become: true
  become_user: apache
  tags: 'upgrade'

- name: get current nextcloud version, before upgrade
  shell: 'php {{ nextcloud_install_dir }}/occ -V'
  become: true
  become_user: apache
  register: nextcloud_installed_version
  changed_when: false
  tags: 'upgrade'

- name: run nextcloud's updater.phar in non-interactive way
  shell: 'php {{ nextcloud_install_dir }}/updater/updater.phar --no-interaction'
  become: true
  become_user: apache
  register: nextcloud_update_result
  changed_when: false # unsure if upgrade has been done -> inform later
  tags: 'upgrade'

- name: get current nextcloud version, after running updater.phar
  shell: 'php {{ nextcloud_install_dir }}/occ -V'
  become: true
  become_user: apache
  register: nextcloud_upgraded_version
  changed_when: false
  tags: 'upgrade'

- name: ensure nextcloud is not in maintenance mode
  command: 'php {{ nextcloud_install_dir }}/occ maintenance:mode --off'
  become: true
  become_user: apache
  tags: 'upgrade'

- name: inform about upgrade
  debug:
    msg: 'nextcloud version has been upgraded from {{ nextcloud_installed_version.stdout  }} to {{ nextcloud_upgraded_version.stdout }}'
  changed_when: true
  when: nextcloud_installed_version.stdout != nextcloud_upgraded_version.stdout
  tags: 'upgrade'
