---
  - name: node_exporter | get and unpack src
    unarchive:
      src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
      dest: /tmp
      remote_src: yes

  - name: node_exporter | ensure folder eixsts
    file:
      path: /opt/prometheus/node_exporter
      state: directory
      owner: prometheus
      group: prometheus

  - name: node_exporter | copy
    shell: cp -rf /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/* /opt/prometheus/node_exporter/

  - name: node_exporter | ensure the right permissions to the src
    file:
      path: /opt/prometheus/node_exporter
      recurse: yes
      owner: prometheus
      group: prometheus

  - name: node_exporter | create service script  (Centos 7)
    template: src=node_exporter.service dest=/etc/systemd/system/node_exporter.service owner=root group=root mode=0644
    when: ansible_distribution == 'CentOS' and ansible_distribution_version | version_compare('7.0', '>=')
    notify: daemon-reload-node_exporter
    tags: [service]

  - name: node_exporter | create service script  (Centos 6)
    template: src=node_exporter.initd dest=/etc/init.d/node_exporter owner=root group=root mode=0744
    when: ansible_distribution == 'CentOS' and ansible_distribution_version | version_compare('7.0', '<')
    notify: restart node_exporter
    tags: [service]

  - name: node_exporter| start and enable node_exporter at boot
    service: name=node_exporter enabled=yes state=started
