---
- import_role: 
    name: geerlingguy.repo-epel

- import_role: 
    name: geerlingguy.repo-remi

- import_role: 
    name: geerlingguy.php-versions

- import_role: 
    name: geerlingguy.php
  vars:
    php_memory_limit: "512M"
    php_max_execution_time: "90"
    php_upload_max_filesize: "2048M"
    php_version: '7.2'
    php_packages_state: "latest"
    php_packages: 
    - php
    - php-cli
    - php-common
    - php-devel
    - php-fpm
    - php-gd
    - php-intl
    - php-json
    - php-ldap
    - php-mbstring
    - php-mcrypt
    - php-opcache
    - php-pdo
    - php-pdo_pgsql
    - php-pecl-apcu
    - php-pecl-redis
    - php-pecl-zip
    - php-posix
    - php-xml
    - php-fpm
    - php-pecl-imagick
    php_enablerepo: "epel,remi-php72"
    php_enable_php_fpm: true
    php_opcache_enable_cli: "1"
    php_opcache_interned_strings_buffer: "8"
    php_opcache_max_accelerated_files: "10000"
    php_opcache_memory_consumption: "128"
    php_opcache_revalidate_freq: "1"  

- import_tasks: 'mod_fastcgi.yml'
  when: not centos_7_installed

- import_role: 
    name: geerlingguy.apache-php-fpm